name: Semgrep

on: [pull_request]

jobs:
  semgrep:
    name: Run semgrep
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        publishToken: ${{ secrets.GITHUB_TOKEN }}
